// This file has been autogenerated from a class added in the UI designer.

using System;
using Pronome.Mac.Visualizer.Graph;
using System.Collections.Generic;
using Pronome.Mac.Visualizer;

namespace Pronome.Mac
{
    public partial class BeatGraphView : AbstractVisualizerView
	{
        protected LinkedList<Ring> Rings;

		/// <summary>
		/// The length of the beat in bpm.
		/// </summary>
		protected double BeatLength;

        public BeatGraphView (IntPtr handle) : base (handle) 
        {
            BeatLength = Metronome.Instance.GetQuartersForCompleteCycle();

			// build the graph, get rings
			Rings = GraphingHelper.BuildGraph(Layer, BeatLength);

            // attach the layer delegate
            AnimationLayer.Delegate = new GraphLayerDelegate()
            {
                BeatLength = BeatLength
            };
        }

        public override void DrawFrame(double bpm)
        {
			// progress the rings. Animate any blinking if needed.
			foreach (Ring ring in Rings)
			{
				ring.Progress(bpm);
			}

            // draw the needle last
            ((GraphLayerDelegate)AnimationLayer.Delegate).ElapsedBpm = bpm;
            AnimationLayer.SetNeedsDisplay();
        }
    }
}
