// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Pronome
{
    public partial class AdditionalSettingsController : NSViewController
    {
        #region Public Properties
        [Export("Settings")]
        public UserSettings Settings
        {
            get => UserSettings.GetSettings();
        }

        [Export("Metronome")]
        public Metronome Metronome
        {
            get => Metronome.Instance;
        }
        #endregion

        #region Constructors
        public AdditionalSettingsController(IntPtr handle) : base(handle)
        {
        }
        #endregion

        #region Actions
        /// <summary>
        /// Opens dialog to get the seconds duration to export to a wav file.
        /// </summary>
        /// <param name="sender">Sender.</param>
        partial void ExportWavFileAction(NSObject sender)
        {
            // should use a modal segue instead...
        }

        /// <summary>
        /// Starts playing out to a wav file.
        /// </summary>
        /// <param name="sender">Sender.</param>
        partial void RecordWavFileAction(NSObject sender)
        {

        }
        #endregion
    }
}
