// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Pronome.Mac
{
    public partial class ExportWavDialog : NSViewController
    {
        #region Computed properties
        string _fileSize;
        [Export("FileSize")]
        public string FileSize
        {
            get => _fileSize;
            set
            {
                WillChangeValue("FileSize");
                _fileSize = value;
                DidChangeValue("FileSize");
            }
        }

        double BeatLengthSeconds;
        [Export("CanUseBeatLength")]
        public bool CanUseBeatLength
        {
            get
            {
                if (BeatLengthSeconds == 0)
                {
                    BeatLengthSeconds = Metronome.Instance.ConvertBpmToSamples(Metronome.Instance.GetQuartersForCompleteCycle()) / Metronome.SampleRate;
                }
                // don't use beat length if > 5 hours
                return BeatLengthSeconds < 60 * 60 * 5;
            }
        }

        bool _useBeatLength;
        [Export("UseBeatLength")]
        public bool UseBeatLength
        {
            get => _useBeatLength;
            set
            {
                WillChangeValue("UseBeatLength");
                Seconds = (nfloat)BeatLengthSeconds;
                _useBeatLength = value;
                DidChangeValue("UseBeatLength");
            }
        }

        nfloat _seconds = 5;
        [Export("Seconds")]
        public nfloat Seconds
        {
            get => _seconds;
            set
            {
                WillChangeValue("Seconds");
                WillChangeValue("FileSize");
                _seconds = value;
                _fileSize = (_seconds * .18).ToString("F2") + "MB";
                DidChangeValue("Seconds");
                DidChangeValue("FileSize");
            }
        }
        #endregion

        #region Public fields
        public NSViewController Presentor;
        #endregion

        #region Constructors
        public ExportWavDialog(IntPtr handle) : base(handle)
        {
        }
        #endregion

        #region Actions
        partial void ExportButtonAction(NSObject sender)
        {
			// make save dialog
			var dlg = new NSSavePanel();
			dlg.Title = "Save Wav File";
			dlg.AllowedFileTypes = new string[] { "wav" };

			if (dlg.RunModal() == 1)
			{
				NSUrl url = dlg.Url;

				if (url != null)
				{
					string path = url.Path;

                    Metronome.Instance.Mixer.RenderToFile(path, Seconds);
				}
			}

            CloseDialog();
        }

        partial void CancelButtonAction(NSObject sender)
        {
            CloseDialog();
        }
        #endregion

        #region Private Methods
        void CloseDialog()
        {
			Presentor.DismissViewController(this);
		}
        #endregion
    }
}
