// This file has been autogenerated from a class added in the UI designer.

using System;
using Pronome.Mac.OptionsWindow;
using Foundation;
using AppKit;

namespace Pronome.Mac
{
    public partial class OptionsRightViewController : NSViewController
    {
        #region Constructors
        public OptionsRightViewController(IntPtr handle) : base(handle)
        {
        }
        #endregion

        #region Public Methods
        public void ShowView(SubviewType type)
        {
            // take action based on requested type
            switch(type)
            {
                case SubviewType.AdditionalSettings:
                    PerformSegue("AdditionalSettingsSegue", this);
                    break;
                case SubviewType.CustomSoundLibrary:
                    PerformSegue("CustomSoundLibrarySegue", this);
                    break;
                case SubviewType.IntervallicMuting:
                    PerformSegue("IntervallicMutingSegue", this);
                    break;
                case SubviewType.RandomMuting:
                    PerformSegue("RandomMutingSegue", this);
                    break;
                case SubviewType.SaveAndLoad:
                    PerformSegue("SaveAndLoadSegue", this);
                    break;
                case SubviewType.Visuals:
                    PerformSegue("VisualsSegue", this);
                    break;
                case SubviewType.WavFileCreation:
                    PerformSegue("WavFileCreationSegue", this);
                    break;
            }
        }
        #endregion
    }
}
