// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Pronome
{
	public partial class OptionsWindowController : NSWindowController
	{
		public OptionsWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
