// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Pronome.Mac
{
	public partial class BeatGraphWindow : NSWindow
	{
		public BeatGraphWindow (IntPtr handle) : base (handle)
		{
		}

        public override NSColor BackgroundColor
        {
            get
            {
                return NSColor.Black;
            }
            set
            {
                base.BackgroundColor = value;
            }
        }
	}
}
