// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Pronome.Mac.Editor.Groups;

namespace Pronome.Mac
{
	public partial class MultGroupDialog : NSViewController
	{
		public NSViewController Presentor;

        public Multiply Group;

        string _factor = "1";
        [Export("Factor")]
        public string Factor
        {
            get => _factor;
            set
            {
                WillChangeValue("Factor");
                if (!string.IsNullOrEmpty(value) && BeatCell.TryParse(value, out double val))
                {
					_factor = value;

                    if (Group != null)
                    {
						Group.FactorValue = value;
                        Group.Factor = val;
                    }
                }
                DidChangeValue("Factor");
            }
        }

		public MultGroupDialog (IntPtr handle) : base (handle)
		{
		}

		partial void AcceptAction(NSObject sender)
		{
			Close();

			Accepted?.Invoke(null, null);
		}

		partial void CancelAction(NSObject sender)
		{
			Close();

			Canceled?.Invoke(null, null);
		}

		private void Close()
		{
			Presentor.DismissViewController(this);
		}

		public event EventHandler Accepted;

		public event EventHandler Canceled;
	}
}
