// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Pronome.Mac.Editor.Groups;

namespace Pronome.Mac
{
    public partial class RepeatGroupDialog : NSViewController
    {
        public NSViewController Presentor;

        public Repeat Group;

        #region Computed Properties
        nint _times = 2;
        [Export("Times")]
        public nint Times
        {
            get => _times;
            set
            {
                WillChangeValue("Times");
                if (value > 1 && value <= 500)
                {
                    _times = value;
                    Group.Times = (int)_times;
                }
                DidChangeValue("Times");
            }
        }

        string _ltm;
        [Export("Ltm")]
        public string Ltm
        {
            get => _ltm;
            set
            {
                WillChangeValue("Ltm");
                if (BeatCell.TryParse(value, out double bpm))
                {
                    _ltm = value;
                    Group.LastTermModifier = value;
                }
                DidChangeValue("Ltm");
            }
        }
        #endregion

        public RepeatGroupDialog (IntPtr handle) : base (handle)
		{
		}

        partial void AcceptAction(NSObject sender)
        {
            Close();

            Accepted?.Invoke(null, null);
        }

        partial void CancelAction(NSObject sender)
        {
            Close();

            Canceled?.Invoke(null, null);
        }

        private void Close()
        {
            Presentor.DismissViewController(this);
        }

        public event EventHandler Accepted;

        public event EventHandler Canceled;
	}
}
