// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Pronome
{
	public partial class MainWindow : NSWindow
	{
		public MainWindow (IntPtr handle) : base (handle)
		{
		}

        public override NSColor BackgroundColor
        {
            get
            {
                return NSColor.FromRgb(0,14,192);
            }
            set
            {
                base.BackgroundColor = value;
            }
        }
    }
}
