// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Pronome
{
    public partial class TransportViewController : NSViewController
    {
        public TransportViewController(IntPtr handle) : base(handle)
        {
        }

        #region Computed Properties
        /// <summary>
        /// Gets the metronome instance.
        /// </summary>
        /// <value>The metronome.</value>
        [Export("Metronome")]
        public Metronome Metronome
        {
            get => Metronome.Instance;
        }
        #endregion

        #region Override Methods
        /// <summary>
        /// Creates a new layer and adds it to the interface
        /// </summary>
        /// <param name="sender">Sender.</param>
        partial void NewLayerAction(NSObject sender)
        {
            var parent = ParentViewController as NSSplitViewController;
            // get the collection view controller
            var layerViewC = parent.SplitViewItems[1].ViewController as LayerViewController;

            layerViewC.AddLayer(new Layer());
        }

        partial void PlayButtonAction(NSObject sender)
        {
            if (Metronome.Instance.Play())
            {
                // disable the play button
                PlayButton.Enabled = false;
                // enable the pause and stop buttons
                PauseButton.Enabled = true;
                StopButton.Enabled = true;
            }
        }

        partial void PauseButtonAction(NSObject sender)
        {
            if (Metronome.Instance.Pause())
            {
                // enable the play button
                PlayButton.Enabled = true;
                // disable the pause button
                PauseButton.Enabled = false;
            }
        }

        partial void StopButtonAction(NSObject sender)
        {
            if (Metronome.Instance.Stop())
            {
                // enable the play button
                PlayButton.Enabled = true;
                // disable the pause and stop buttons
                PauseButton.Enabled = false;
                StopButton.Enabled = false;
            }
        }
        #endregion
    }
}
