// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Pronome
{
    public partial class LayerViewController : NSViewController
    {
        /// <summary>
        /// Holds a reference to the instance.
        /// </summary>
        static public LayerViewController Instance;

        #region Computed Properties
        /// <summary>
        /// Gets or sets the datasource that provides data to display in the 
        /// collection view.
        /// </summary>
        /// <value>The datasource.</value>
        public LayerCollectionViewDataSource Datasource { get; set; }
        #endregion

        #region Constructors
        public LayerViewController(IntPtr handle) : base(handle)
        {
            Instance = this;
        }
        #endregion

        #region Overriden Methods
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Initialize collection view
            ConfigureCollectionView();
            PopulateWithData();
        }
        #endregion

        #region Public Methods
        /// <summary>
        /// Adds the new layer.
        /// </summary>
        /// <param name="layer">Layer.</param>
        public void AddLayer(Layer layer)
        {
            // add the layer to the datasource
            Datasource.Data.Add(layer);

            LayerCollection.ReloadData();
        }

        /// <summary>
        /// Removes the layer.
        /// </summary>
        /// <param name="layer">Layer.</param>
        public void RemoveLayer(Layer layer)
        {
            Datasource.Data.Remove(layer);

            LayerCollection.ReloadData();
            // remove from metronome
            Metronome.Instance.RemoveLayer(layer);
        }
        #endregion

        #region Private Methods
        private void ConfigureCollectionView()
        {
            LayerCollection.RegisterClassForItem(typeof(LayerItemController), "LayerCell");

            // Create flow layout
            var flowLayout = new NSCollectionViewFlowLayout()
            {
                ItemSize = new CoreGraphics.CGSize(470, 150),
                SectionInset = new NSEdgeInsets(10, 10, 10, 20),
                MinimumLineSpacing = 10,
                MinimumInteritemSpacing = 10
            };
            LayerCollection.WantsLayer = true;

            // Setup collection view
            LayerCollection.CollectionViewLayout = flowLayout;
        }

        private void PopulateWithData()
        {
            // Make datasource
            Datasource = new LayerCollectionViewDataSource(LayerCollection);

            Datasource.Data.Add(new Layer());

            // Populate collection view
            LayerCollection.ReloadData();
        }
        #endregion
    }
}
