// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Pronome.Mac.Visualizer.Bounce;
using System.Linq;
using CoreGraphics;

namespace Pronome.Mac
{
    public partial class BounceView : AbstractVisualizerView
    {
        #region Protected properties
        protected Lane[] Lanes;

        protected Ball[] Balls;
        #endregion

        public BounceView(IntPtr handle) : base(handle)
        {
            // create the elements
            Lanes = Metronome.Instance.Layers.Select(x => new Lane(x)).ToArray();
            Balls = Metronome.Instance.Layers.Select(x => new Ball(x)).ToArray();

            AnimationLayer.Delegate = new BounceLayerDelegate();

            // draw the framework
            AnimationLayer.SetNeedsDisplay();
        }

        #region public methods
        public override void DrawFrame(double bpm)
        {
            // animate the balls

            // animate the tick marks
        }
        #endregion

        #region protected methods
        protected override CGRect GetFrame(nfloat winWidth, nfloat winHeight)
        {
            nfloat min = winWidth < winHeight ? winWidth : winHeight;

            // a value from 0 to 1
            nfloat spread = UserSettings.GetSettings().BounceWidthPad;
            nfloat width, height, xPos, yPos;

            var ratio = winHeight / winWidth;
            var spreadRatio = 1 / (spread + 1);

            if (spreadRatio > ratio)
            {
                height = winHeight;
                width = height * (spread + 1);

                yPos = 0;
                xPos = winWidth / 2 - width / 2;
            }
            else
            {
                width = winWidth;
				height = width / (1 + spread);

                xPos = 0;
                yPos = winHeight / 2 - height / 2;
            }

            return new CGRect(xPos, yPos, width, height);
        }
        #endregion
    }
}
